Added stringer() and started implementation. Also resolved a lot of memory allocation issues (got --enable-free to actually mean something and to work). Also fixed the configuration script to not look for libtclx unless --with-tclx is given.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5427,6 +5427,8 @@ echo "$as_me: error: ${with_tclxconfig} directory doesn't contain tclxConfig.sh"
    { (exit 1); exit 1; }; }
 		    fi
 		fi
+	    else
+		ac_cv_c_tclxconfig='no_tclx'
 	    fi
 
 	    # then check for a private Tcl installation
@@ -5473,26 +5475,28 @@ fi
 
 	if test x"${ac_cv_c_tclxconfig}" = x ; then
 	    TCLX_BIN_DIR="# no Tcl configs found"
-	    { echo "$as_me:5476: WARNING: Can't find Tcl configuration definitions" >&5
+	    { echo "$as_me:5478: WARNING: Can't find Tcl configuration definitions" >&5
 echo "$as_me: WARNING: Can't find Tcl configuration definitions" >&2;}
 	    exit 0
 	else
-	    no_tclx=
-	    TCLX_BIN_DIR=${ac_cv_c_tclxconfig}
-	    echo "$as_me:5482: result: found $TCLX_BIN_DIR/tclxConfig.sh" >&5
+	    if test x"${ac_cv_c_tclxconfig}" != x"no_tclx" ; then
+		no_tclx=
+		TCLX_BIN_DIR=${ac_cv_c_tclxconfig}
+		echo "$as_me:5485: result: found $TCLX_BIN_DIR/tclxConfig.sh" >&5
 echo "${ECHO_T}found $TCLX_BIN_DIR/tclxConfig.sh" >&6
+	    fi
 	fi
     fi
 
-    echo "$as_me:5487: checking for existence of $TCLX_BIN_DIR/tclxConfig.sh" >&5
+    echo "$as_me:5491: checking for existence of $TCLX_BIN_DIR/tclxConfig.sh" >&5
 echo $ECHO_N "checking for existence of $TCLX_BIN_DIR/tclxConfig.sh... $ECHO_C" >&6
 
     if test -f "$TCLX_BIN_DIR/tclxConfig.sh" ; then
-        echo "$as_me:5491: result: loading" >&5
+        echo "$as_me:5495: result: loading" >&5
 echo "${ECHO_T}loading" >&6
 	. $TCLX_BIN_DIR/tclxConfig.sh
     else
-        echo "$as_me:5495: result: file not found" >&5
+        echo "$as_me:5499: result: file not found" >&5
 echo "${ECHO_T}file not found" >&6
     fi
 
@@ -5507,19 +5511,19 @@ fi
 if test "${with_module_path+set}" = set; then
   withval="$with_module_path"
   MODULEPATH="$withval"
-	echo "$as_me:5510: result: MODULEPATH = $with_module_path" >&5
+	echo "$as_me:5514: result: MODULEPATH = $with_module_path" >&5
 echo "${ECHO_T}MODULEPATH = $with_module_path" >&6
 	cat >>confdefs.h <<EOF
 #define MODULEPATH "$withval"
 EOF
 
 else
-  { echo "$as_me:5517: WARNING: if using '--with-module-path': need to specify a path!" >&5
+  { echo "$as_me:5521: WARNING: if using '--with-module-path': need to specify a path!" >&5
 echo "$as_me: WARNING: if using '--with-module-path': need to specify a path!" >&2;}
 	if test "$withval" = "no" || test "$withval" = "yes"; then
 		withval="/usr/local/Modules/modulefiles"
 	fi
-	{ echo "$as_me:5522: WARNING: will use MODULEPATH=$withval" >&5
+	{ echo "$as_me:5526: WARNING: will use MODULEPATH=$withval" >&5
 echo "$as_me: WARNING: will use MODULEPATH=$withval" >&2;}
 	MODULEPATH="$withval"
 	cat >>confdefs.h <<EOF
@@ -5532,19 +5536,19 @@ fi;
 if test "${with_version_path+set}" = set; then
   withval="$with_version_path"
   VERSIONPATH="$withval"
-	echo "$as_me:5535: result: VERSIONPATH = $with_version_path" >&5
+	echo "$as_me:5539: result: VERSIONPATH = $with_version_path" >&5
 echo "${ECHO_T}VERSIONPATH = $with_version_path" >&6
 	cat >>confdefs.h <<EOF
 #define VERSIONPATH "$withval"
 EOF
 
 else
-  { echo "$as_me:5542: WARNING: if using '--with-version-path': need to specify a path!" >&5
+  { echo "$as_me:5546: WARNING: if using '--with-version-path': need to specify a path!" >&5
 echo "$as_me: WARNING: if using '--with-version-path': need to specify a path!" >&2;}
 	if test "$withval" = "no" || test "$withval" = "yes"; then
 		withval="$prefix/Modules/versions"
 	fi
-	{ echo "$as_me:5547: WARNING: will use VERSIONPATH=$withval" >&5
+	{ echo "$as_me:5551: WARNING: will use VERSIONPATH=$withval" >&5
 echo "$as_me: WARNING: will use VERSIONPATH=$withval" >&2;}
 	VERSIONPATH="$withval"
 	cat >>confdefs.h <<EOF
@@ -5574,7 +5578,7 @@ fi;
 if test "${with_etc_path+set}" = set; then
   withval="$with_etc_path"
   if test "$withval" = "no" || test "$withval" = "yes"; then
-	{ echo "$as_me:5577: WARNING: if using '--with-etc-path': need to specify a path! Using /etc" >&5
+	{ echo "$as_me:5581: WARNING: if using '--with-etc-path': need to specify a path! Using /etc" >&5
 echo "$as_me: WARNING: if using '--with-etc-path': need to specify a path! Using /etc" >&2;}
 		withval="/etc"
 	fi
@@ -5588,7 +5592,7 @@ fi;
 if test "${with_skel_path+set}" = set; then
   withval="$with_skel_path"
   if test "$withval" = "no" || test "$withval" = "yes"; then
-	{ echo "$as_me:5591: WARNING: if using '--with-skel-path': need to specify a path! Using /etc/skel" >&5
+	{ echo "$as_me:5595: WARNING: if using '--with-skel-path': need to specify a path! Using /etc/skel" >&5
 echo "$as_me: WARNING: if using '--with-skel-path': need to specify a path! Using /etc/skel" >&2;}
 		withval="/etc/skel"
 	fi
@@ -5697,7 +5701,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:5700: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:5704: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -5873,7 +5877,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:5876: error: ambiguous option: $1
+    { { echo "$as_me:5880: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -5892,7 +5896,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:5895: error: unrecognized option: $1
+  -*) { { echo "$as_me:5899: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -5985,7 +5989,7 @@ do
   "testsuite/modules.50-cmds/100-loglevel.exp" ) CONFIG_FILES="$CONFIG_FILES testsuite/modules.50-cmds/100-loglevel.exp" ;;
   "default" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:5988: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:5992: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -6236,7 +6240,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:6239: creating $ac_file" >&5
+    { echo "$as_me:6243: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -6254,7 +6258,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:6257: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:6261: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -6267,7 +6271,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:6270: error: cannot find input file: $f" >&5
+           { { echo "$as_me:6274: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -6328,7 +6332,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:6331: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:6335: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -6339,7 +6343,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:6342: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:6346: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -6352,7 +6356,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:6355: error: cannot find input file: $f" >&5
+           { { echo "$as_me:6359: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -6469,7 +6473,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:6472: $ac_file is unchanged" >&5
+      { echo "$as_me:6476: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
