* Updated the config/tcl.m4 (used by configure)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -253,7 +253,7 @@ exec 6>&1
 #
 ac_default_prefix=/usr/local
 ac_config_libobj_dir=.
-cross_compiling=yes
+cross_compiling=no
 subdirs=
 MFLAGS=
 MAKEFLAGS=
@@ -309,7 +309,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot WANTS_VERSIONING VERSIONING NOTVERSIONING DATE DEFAULTPATH BASEPREFIX CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP UNAME X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS _CPPSTDIN _PHOST RUNTEST STATIC WITH_LOGGING TCL_DBGX TCL_BIN_DIR TCL_SRC_DIR TCL_LIB_FILE TCL_LIBS TCL_DEFS TCL_SHLIB_LD_LIBS TCL_EXTRA_CFLAGS TCL_LD_FLAGS TCL_STUB_LIB_FILE TCL_LIB_SPEC TCL_BUILD_LIB_SPEC TCL_STUB_LIB_SPEC TCL_BUILD_STUB_LIB_SPEC TCL_INCLUDES TCLX_FULL_VERSION TCLX_VERSION TCLX_DEFS TCLX_LIBS TCLX_BUILD_LIB_SPEC TCLX_LIB_SPEC TCLX_LD_SEARCH_FLAGS MODULEPATH VERSIONPATH AUTOLOADPATH ETCPATH SKELPATH DOT_EXT EXTDIR LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot WANTS_VERSIONING VERSIONING NOTVERSIONING DATE DEFAULTPATH BASEPREFIX CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP UNAME X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS _CPPSTDIN _PHOST RUNTEST STATIC WITH_LOGGING TCL_VERSION TCL_BIN_DIR TCL_SRC_DIR TCL_LIB_FILE TCL_LIB_FLAG TCL_LIB_SPEC TCL_STUB_LIB_FILE TCL_STUB_LIB_FLAG TCL_STUB_LIB_SPEC TCL_INCLUDE_SPEC TCLX_LIB_SPEC TCLX_FULL_VERSION TCLX_VERSION TCLX_DEFS TCLX_LIBS TCLX_BUILD_LIB_SPEC TCLX_LD_SEARCH_FLAGS MODULEPATH VERSIONPATH AUTOLOADPATH ETCPATH SKELPATH DOT_EXT EXTDIR LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -925,9 +925,10 @@ Optional Packages:
                           specify a pattern for trace [no]
   --with-trace-apropos=<value>
                           specify a pattern for trace [no]
-  --with-tcl              directory containing tcl configuration (tclConfig.sh)
-  --with-tclinclude       directory containing the public Tcl header files.
-  --with-tclx             directory containing tclx configuration (tclxConfig.sh)
+  --with-tcl=<dir>        directory containing tcl configuration
+                          (tclConfig.sh) [searches]
+  --with-tclx=<dir>       directory containing tclx configuration
+                          (tclxConfig.sh) [searches]
   --with-module-path=<path>
                           use module path=<path>
                           [PREFIX/Modules/modulefiles]
@@ -6845,7 +6846,7 @@ C-shell can handle large environment variables or not." >&5
 echo "$as_me: WARNING: You must specify --with-split-size=<size>
 when cross compiling ... configure can not guess whether the target system
 C-shell can handle large environment variables or not." >&2;}
-elif test $em_split_size_total -gt 8000 ; then
+elif test $em_split_size_total -gt 4000 ; then
 	em_split_size="no"
 	echo "$as_me:$LINENO: result: yes - $em_split_size_total > 4000" >&5
 echo "${ECHO_T}yes - $em_split_size_total > 4000" >&6
@@ -7726,6 +7727,11 @@ if test "${with_tcl+set}" = set; then
   withval="$with_tcl"
   with_tclconfig=${withval}
 fi;
+	if test x"$withval" = x"no" ; then
+	   { { echo "$as_me:$LINENO: error: Environment Modules can not be built without Tcl!" >&5
+echo "$as_me: error: Environment Modules can not be built without Tcl!" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
 	echo "$as_me:$LINENO: checking for Tcl configuration" >&5
 echo $ECHO_N "checking for Tcl configuration... $ECHO_C" >&6
 	if test "${ac_cv_c_tclconfig+set}" = set; then
@@ -7748,10 +7754,16 @@ echo "$as_me: error: ${with_tclconfig} directory doesn't contain tclConfig.sh" >
 	    if test x"${ac_cv_c_tclconfig}" = x ; then
 		for i in \
 			../tcl \
+			`ls -dr ../tcl[8-9].[0-9].[0-9]* 2>/dev/null` \
+			`ls -dr ../tcl[8-9].[0-9] 2>/dev/null` \
 			`ls -dr ../tcl[8-9].[0-9]* 2>/dev/null` \
 			../../tcl \
+			`ls -dr ../../tcl[8-9].[0-9].[0-9]* 2>/dev/null` \
+			`ls -dr ../../tcl[8-9].[0-9] 2>/dev/null` \
 			`ls -dr ../../tcl[8-9].[0-9]* 2>/dev/null` \
 			../../../tcl \
+			`ls -dr ../../../tcl[8-9].[0-9].[0-9]* 2>/dev/null` \
+			`ls -dr ../../../tcl[8-9].[0-9] 2>/dev/null` \
 			`ls -dr ../../../tcl[8-9].[0-9]* 2>/dev/null` ; do
 		    if test -f "$i/unix/tclConfig.sh" ; then
 			ac_cv_c_tclconfig=`(cd $i/unix; pwd)`
@@ -7762,9 +7774,11 @@ echo "$as_me: error: ${with_tclconfig} directory doesn't contain tclConfig.sh" >
 
 	    # check in a few common install locations
 	    if test x"${ac_cv_c_tclconfig}" = x ; then
-		for i in `ls -d ${prefix}/lib 2>/dev/null` \
+		for i in `ls -d ${libdir} 2>/dev/null` \
+			`ls -d /usr/local/lib 2>/dev/null` \
+			`ls -d /usr/contrib/lib 2>/dev/null` \
 			`ls -d /usr/lib 2>/dev/null` \
-			`ls -d /usr/local/lib 2>/dev/null` ; do
+			; do
 		    if test -f "$i/tclConfig.sh" ; then
 			ac_cv_c_tclconfig=`(cd $i; pwd)`
 			break
@@ -7776,6 +7790,8 @@ echo "$as_me: error: ${with_tclconfig} directory doesn't contain tclConfig.sh" >
 	    if test x"${ac_cv_c_tclconfig}" = x ; then
 		for i in \
 			${srcdir}/../tcl \
+			`ls -dr ${srcdir}/../tcl[8-9].[0-9].[0-9]* 2>/dev/null` \
+			`ls -dr ${srcdir}/../tcl[8-9].[0-9] 2>/dev/null` \
 			`ls -dr ${srcdir}/../tcl[8-9].[0-9]* 2>/dev/null` ; do
 		    if test -f "$i/unix/tclConfig.sh" ; then
 		    ac_cv_c_tclconfig=`(cd $i/unix; pwd)`
@@ -7814,91 +7830,43 @@ echo "${ECHO_T}file not found" >&6
     fi
 
     #
-    # The eval is required to do the TCL_DBGX substitution in the
-    # TCL_LIB_FILE variable
+    # If the TCL_BIN_DIR is the build directory (not the install directory),
+    # then set the common variable name to the value of the build variables.
+    # For example, the variable TCL_LIB_SPEC will be set to the value
+    # of TCL_BUILD_LIB_SPEC. An extension should make use of TCL_LIB_SPEC
+    # instead of TCL_BUILD_LIB_SPEC since it will work with both an
+    # installed and uninstalled version of Tcl.
     #
 
-    eval TCL_LIB_FILE=${TCL_LIB_FILE}
-    eval TCL_LIB_FLAG=${TCL_LIB_FLAG}
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-    echo "$as_me:$LINENO: checking for Tcl public headers" >&5
-echo $ECHO_N "checking for Tcl public headers... $ECHO_C" >&6
-
-
-# Check whether --with-tclinclude or --without-tclinclude was given.
-if test "${with_tclinclude+set}" = set; then
-  withval="$with_tclinclude"
-  with_tclinclude=${withval}
-fi;
-
-    if test x"${with_tclinclude}" != x ; then
-	if test -f "${with_tclinclude}/tcl.h" ; then
-	    ac_cv_c_tclh=${with_tclinclude}
-	else
-	    { { echo "$as_me:$LINENO: error: ${with_tclinclude} directory does not contain Tcl public header file tcl.h" >&5
-echo "$as_me: error: ${with_tclinclude} directory does not contain Tcl public header file tcl.h" >&2;}
-   { (exit 1); exit 1; }; }
-	fi
-    else
-	if test "${ac_cv_c_tclh+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-
-	    # Use the value from --with-tclinclude, if it was given
-
-	    if test x"${with_tclinclude}" != x ; then
-		ac_cv_c_tclh=${with_tclinclude}
-	    else
-		# Check in the includedir, if --prefix was specified
-
-		eval "temp_includedir=${includedir}"
-		for i in \
-			`ls -d ${temp_includedir} 2>/dev/null` \
-			/usr/include /usr/local/include ; do
-		    if test -f "$i/tcl.h" ; then
-			ac_cv_c_tclh=$i
-			break
-		    fi
-		done
-	    fi
-
-fi
-
+    if test -f $TCL_BIN_DIR/Makefile ; then
+        TCL_LIB_SPEC=${TCL_BUILD_LIB_SPEC}
+        TCL_STUB_LIB_SPEC=${TCL_BUILD_STUB_LIB_SPEC}
+        TCL_STUB_LIB_PATH=${TCL_BUILD_STUB_LIB_PATH}
     fi
 
-    # Print a message based on how we determined the include path
+    #
+    # eval is required to do the TCL_DBGX substitution
+    #
 
-    if test x"${ac_cv_c_tclh}" = x ; then
-	{ { echo "$as_me:$LINENO: error: tcl.h not found.  Please specify its location with --with-tclinclude" >&5
-echo "$as_me: error: tcl.h not found.  Please specify its location with --with-tclinclude" >&2;}
-   { (exit 1); exit 1; }; }
-    else
-	echo "$as_me:$LINENO: result: ${ac_cv_c_tclh}" >&5
-echo "${ECHO_T}${ac_cv_c_tclh}" >&6
-    fi
+    eval "TCL_LIB_FILE=\"${TCL_LIB_FILE}\""
+    eval "TCL_LIB_FLAG=\"${TCL_LIB_FLAG}\""
+    eval "TCL_LIB_SPEC=\"${TCL_LIB_SPEC}\""
 
-    # Convert to a native path and substitute into the output files.
+    eval "TCL_STUB_LIB_FILE=\"${TCL_STUB_LIB_FILE}\""
+    eval "TCL_STUB_LIB_FLAG=\"${TCL_STUB_LIB_FLAG}\""
+    eval "TCL_STUB_LIB_SPEC=\"${TCL_STUB_LIB_SPEC}\""
 
-#    INCLUDE_DIR_NATIVE=`${CYGPATH} ${ac_cv_c_tclh}`
 
-    TCL_INCLUDES=-I${ac_cv_c_tclh}
+
+
+
+
+
+
+
+
+
+
 
 
 
@@ -7908,7 +7876,7 @@ echo "${ECHO_T}${ac_cv_c_tclh}" >&6
     #
     # Ok, lets find the tclx configuration
     # First, look for one uninstalled.
-    # the alternative search directory is invoked by --with-tclx
+    # the alternative search directory is invoked by --with-tcl
     #
 
     if test x"${no_tclx}" = x ; then
@@ -7920,36 +7888,43 @@ if test "${with_tclx+set}" = set; then
   withval="$with_tclx"
   with_tclxconfig=${withval}
 fi;
-	echo "$as_me:$LINENO: checking for Tcl configuration" >&5
-echo $ECHO_N "checking for Tcl configuration... $ECHO_C" >&6
-	if test "${ac_cv_c_tclxconfig+set}" = set; then
+	if test x"$withval" = x"no" ; then
+		{ echo "$as_me:$LINENO: Skipping Tclx configuration" >&5
+echo "$as_me: Skipping Tclx configuration" >&6;}
+		no_tclx=true
+	else #{
+		echo "$as_me:$LINENO: checking for Tclx configuration" >&5
+echo $ECHO_N "checking for Tclx configuration... $ECHO_C" >&6
+		if test "${ac_cv_c_tclxconfig+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
 
 
 	    # First check to see if --with-tclx was specified.
 	    if test x"${with_tclxconfig}" != x ; then
-		if test x"${with_tclxconfig}" != x"yes" ; then
-		    if -f "${with_tclxconfig}/tclxConfig.sh" ; then
-			ac_cv_c_tclxconfig=`(cd ${with_tclxconfig}; pwd)`
-		    else
-			{ { echo "$as_me:$LINENO: error: ${with_tclxconfig} directory doesn't contain tclxConfig.sh" >&5
-echo "$as_me: error: ${with_tclxconfig} directory doesn't contain tclxConfig.sh" >&2;}
+		if test -f "${with_tclxconfig}/tclxConfig.sh" ; then
+		    ac_cv_c_tclxconfig=`(cd ${with_tclxconfig}; pwd)`
+		else
+		    { { echo "$as_me:$LINENO: error: ${with_tclxconfig} directory does not contain tclxConfig.sh" >&5
+echo "$as_me: error: ${with_tclxconfig} directory does not contain tclxConfig.sh" >&2;}
    { (exit 1); exit 1; }; }
-		    fi
 		fi
-	    else
-		ac_cv_c_tclxconfig='no_tclx'
 	    fi
 
-	    # then check for a private Tcl installation
+	    # then check for a private Tclx installation
 	    if test x"${ac_cv_c_tclxconfig}" = x ; then
 		for i in \
 			../tclx \
+			`ls -dr ../tclx[8-9].[0-9].[0-9]* 2>/dev/null` \
+			`ls -dr ../tclx[8-9].[0-9] 2>/dev/null` \
 			`ls -dr ../tclx[8-9].[0-9]* 2>/dev/null` \
 			../../tclx \
+			`ls -dr ../../tclx[8-9].[0-9].[0-9]* 2>/dev/null` \
+			`ls -dr ../../tclx[8-9].[0-9] 2>/dev/null` \
 			`ls -dr ../../tclx[8-9].[0-9]* 2>/dev/null` \
 			../../../tclx \
+			`ls -dr ../../../tclx[8-9].[0-9].[0-9]* 2>/dev/null` \
+			`ls -dr ../../../tclx[8-9].[0-9] 2>/dev/null` \
 			`ls -dr ../../../tclx[8-9].[0-9]* 2>/dev/null` ; do
 		    if test -f "$i/unix/tclxConfig.sh" ; then
 			ac_cv_c_tclxconfig=`(cd $i/unix; pwd)`
@@ -7960,9 +7935,11 @@ echo "$as_me: error: ${with_tclxconfig} directory doesn't contain tclxConfig.sh"
 
 	    # check in a few common install locations
 	    if test x"${ac_cv_c_tclxconfig}" = x ; then
-		for i in `ls -d ${prefix}/lib 2>/dev/null` \
+		for i in `ls -d ${libdir} 2>/dev/null` \
+			`ls -d /usr/local/lib 2>/dev/null` \
+			`ls -d /usr/contrib/lib 2>/dev/null` \
 			`ls -d /usr/lib 2>/dev/null` \
-			`ls -d /usr/local/lib 2>/dev/null` ; do
+			; do
 		    if test -f "$i/tclxConfig.sh" ; then
 			ac_cv_c_tclxconfig=`(cd $i; pwd)`
 			break
@@ -7974,6 +7951,8 @@ echo "$as_me: error: ${with_tclxconfig} directory doesn't contain tclxConfig.sh"
 	    if test x"${ac_cv_c_tclxconfig}" = x ; then
 		for i in \
 			${srcdir}/../tclx \
+			`ls -dr ${srcdir}/../tclx[8-9].[0-9].[0-9]* 2>/dev/null` \
+			`ls -dr ${srcdir}/../tclx[8-9].[0-9] 2>/dev/null` \
 			`ls -dr ${srcdir}/../tclx[8-9].[0-9]* 2>/dev/null` ; do
 		    if test -f "$i/unix/tclxConfig.sh" ; then
 		    ac_cv_c_tclxconfig=`(cd $i/unix; pwd)`
@@ -7985,22 +7964,25 @@ echo "$as_me: error: ${with_tclxconfig} directory doesn't contain tclxConfig.sh"
 fi
 
 
-	if test x"${ac_cv_c_tclxconfig}" = x ; then
-	    TCLX_BIN_DIR="# no Tcl configs found"
-	    { echo "$as_me:$LINENO: WARNING: Can't find Tcl configuration definitions" >&5
-echo "$as_me: WARNING: Can't find Tcl configuration definitions" >&2;}
-	    exit 0
-	else
-	    if test x"${ac_cv_c_tclxconfig}" != x"no_tclx" ; then
-		no_tclx=
-		TCLX_BIN_DIR=${ac_cv_c_tclxconfig}
-		echo "$as_me:$LINENO: result: found $TCLX_BIN_DIR/tclxConfig.sh" >&5
+		if test x"${ac_cv_c_tclxconfig}" = x ; then
+		    TCLX_BIN_DIR="# no Tclx configs found"
+		    { echo "$as_me:$LINENO: WARNING: Can not find Tclx configuration definitions" >&5
+echo "$as_me: WARNING: Can not find Tclx configuration definitions" >&2;}
+		    exit 0
+		else
+		    no_tclx=
+		    TCLX_BIN_DIR=${ac_cv_c_tclxconfig}
+		    echo "$as_me:$LINENO: result: found $TCLX_BIN_DIR/tclxConfig.sh" >&5
 echo "${ECHO_T}found $TCLX_BIN_DIR/tclxConfig.sh" >&6
-	    fi
-	fi
+		fi
+	fi #}
     fi
 
 
+  if test x"$no_tclx" = x"true" ; then
+    TCLX_LIB_SPEC=""
+
+  else
     echo "$as_me:$LINENO: checking for existence of $TCLX_BIN_DIR/tclxConfig.sh" >&5
 echo $ECHO_N "checking for existence of $TCLX_BIN_DIR/tclxConfig.sh... $ECHO_C" >&6
 
@@ -8020,7 +8002,7 @@ echo "${ECHO_T}file not found" >&6
 
 
 
-
+  fi
 
 if test x"$no_tclx" != x"true"; then
 
@@ -8902,27 +8884,22 @@ s,@_PHOST@,$_PHOST,;t t
 s,@RUNTEST@,$RUNTEST,;t t
 s,@STATIC@,$STATIC,;t t
 s,@WITH_LOGGING@,$WITH_LOGGING,;t t
-s,@TCL_DBGX@,$TCL_DBGX,;t t
+s,@TCL_VERSION@,$TCL_VERSION,;t t
 s,@TCL_BIN_DIR@,$TCL_BIN_DIR,;t t
 s,@TCL_SRC_DIR@,$TCL_SRC_DIR,;t t
 s,@TCL_LIB_FILE@,$TCL_LIB_FILE,;t t
-s,@TCL_LIBS@,$TCL_LIBS,;t t
-s,@TCL_DEFS@,$TCL_DEFS,;t t
-s,@TCL_SHLIB_LD_LIBS@,$TCL_SHLIB_LD_LIBS,;t t
-s,@TCL_EXTRA_CFLAGS@,$TCL_EXTRA_CFLAGS,;t t
-s,@TCL_LD_FLAGS@,$TCL_LD_FLAGS,;t t
-s,@TCL_STUB_LIB_FILE@,$TCL_STUB_LIB_FILE,;t t
+s,@TCL_LIB_FLAG@,$TCL_LIB_FLAG,;t t
 s,@TCL_LIB_SPEC@,$TCL_LIB_SPEC,;t t
-s,@TCL_BUILD_LIB_SPEC@,$TCL_BUILD_LIB_SPEC,;t t
+s,@TCL_STUB_LIB_FILE@,$TCL_STUB_LIB_FILE,;t t
+s,@TCL_STUB_LIB_FLAG@,$TCL_STUB_LIB_FLAG,;t t
 s,@TCL_STUB_LIB_SPEC@,$TCL_STUB_LIB_SPEC,;t t
-s,@TCL_BUILD_STUB_LIB_SPEC@,$TCL_BUILD_STUB_LIB_SPEC,;t t
-s,@TCL_INCLUDES@,$TCL_INCLUDES,;t t
+s,@TCL_INCLUDE_SPEC@,$TCL_INCLUDE_SPEC,;t t
+s,@TCLX_LIB_SPEC@,$TCLX_LIB_SPEC,;t t
 s,@TCLX_FULL_VERSION@,$TCLX_FULL_VERSION,;t t
 s,@TCLX_VERSION@,$TCLX_VERSION,;t t
 s,@TCLX_DEFS@,$TCLX_DEFS,;t t
 s,@TCLX_LIBS@,$TCLX_LIBS,;t t
 s,@TCLX_BUILD_LIB_SPEC@,$TCLX_BUILD_LIB_SPEC,;t t
-s,@TCLX_LIB_SPEC@,$TCLX_LIB_SPEC,;t t
 s,@TCLX_LD_SEARCH_FLAGS@,$TCLX_LD_SEARCH_FLAGS,;t t
 s,@MODULEPATH@,$MODULEPATH,;t t
 s,@VERSIONPATH@,$VERSIONPATH,;t t
